### ISSUE TITLE
Add support for deploying to Sonatype OSS / Maven Central

### ISSUE THREAD

**Issue by oconnormi** [connexta/multi-int-store#29]
Some tasks need to be accomplished to deploy artifacts to maven central from CI. See: [Publishing Gradle Projects to Sonatype OSS](https://central.sonatype.org/pages/gradle.html)

# Tasks
- [ ] Ensure generated poms meet the [requirements](https://central.sonatype.org/pages/requirements.html)
- [ ] Add [signing](http://www.gradle.org/docs/current/userguide/signing_plugin.html) plugin
- [ ] Add javadocs jar uploads
- [ ] Add sources jar uploads
